= Configración Módulo READER de Pathfinder

[%hardbreaks]
El lector de Pathfinder es el encargado de leer el archivo específico donde se almacenan los eventos en el equipo de orígen. También es el encargado de asegurarse que el evento no sea leído múltiples veces y de llevar el seguimiento del archivo de log en caso de que el mismo sea alterado (ej, rotación de tamaño)

[TIP] 
====
Los requisitos para la ejecución son los siguientes::

* JDK 1.7.x

Para poder configurar estos requisitos debería remitirse al documento link:README.adoc[Principal] de configuración
====

[[index]]
== OBJETIVO y ESTRUCTURA
Esta sección explica como configurar y correr correctamente el lector de Pathfinder.

 * <<configuracion_reader>>
 * <<configuracion_app>>
 ** <<params>>
 ** <<ejecucion_misma>>
 ** <<ejecucion_diferente>>
 ** <<ejecucion_gral>>

[[configuracion_reader]]
= Configuración del Agente Lector
El lector se *auto configura* si se va a ejecutar en la misma máquina donde corre la aplicación, pero en general esto se hace en máquinas donde se almacenan los archivos de eventos que se leerán y enviarán a Pathfinder.

== Archivo de configuración del Lector
[%hardbreaks]
El archivo de configuración se puede crear a mano antes de ejecutar el lector, si no se crea previamente se crea automáticamente al ejecutarlo por primera vez en el directorio de ejecución configurado. 
El directorio de ejecución se configura por parámetro de ejecución al correr el comando para levantar el agente, _más adelante se revisará este punto_.

 * Crear el archivo `config.json` en un directorio seleccionado, para este caso vamos a utilizar `/opt/agente` (puede ser cualquiera), y lo tendremos en cuenta para cuando vayamos a inicializar el agente mas adelante.
 * Agregar la siguiente información
 
	configuration.pathfinder.url.host=127.0.0.1 #(El host del server donde corre Pahtfinder)
	configuration.pathfinder.url.port=8180 #(El puerto donde corre Pathfinder)
	configuration.pathfinder.url.protocol=http #(El protocolo de comunicación con Pathfinder)
	configuration.pathfinder.url.context=/pathfinder #(El contexto sobre el que corre Pathfidner)
	configuration.health.active=true #(Flag para determinar si el agente envía datos al health externo)
	configuration.health.url.host=127.0.0.1 #(Host donde corre Pathfinder)
	configuration.health.url.port=8180 #(El puerto donde corre el health externo a pathfinder)
	configuration.health.url.context=/pathfinder-health #(Contexto sobre el que corre el health externo de Pathfinder)


[[configuracion_app]]
= Ejecución del Agente Lector
Como vimos anteriormente el agente puede ejecutarse directamente sin crear configuraciones si el mismo se ejecuta en el mismo servidor de Pathfinder. Vamos a proceder a detallar los dos métodos de ejecución.

[[params]]
=== Parámetros posibles para configurar el agente por comando
El agente recibe distintos parámetros de configuración por línea de comando, a continuación se detallan:

* -w Directorio de ejecución, *debe tener los permisos necesarios que el usuario que corre el agente pueda crear archivos en él*
* -h Host de Pathfinder, Se matchea con la propiedad `configuration.pathfinder.url.host`
* -p Puerto de Pathfinder, Se matchea con la propiedad `configuration.pathfinder.url.port`
* -c Contexto de Pathfinder, Se matchea con la propiedad `configuration.pathfinder.url.context`
* -hh Host del Health Pathfinder, Se matchea con la propiedad `configuration.health.url.host`
* -hp Puerto del Health Pathfinder, Se matchea con la propiedad `configuration.health.url.port`
* -hc Contexto del Health Pathfinder, Se matchea con la propiedad `configuration.health.url.context`

[[ejecucion_misma]]
=== Ejecución en misma máquina
Si el agente lector corre sobre el mismo servidor donde corre Pathfinder el comando para ejecutarlo es el siguiente (se utilizará el directorio de trabajo establecido en la sección "<<configuracion_reader>>"):
 
 $ java -jar pathfinder-agent.jar -w /opt/agente 

[[ejecucion_diferente]]
=== Ejecución en diferente máquina
Si el agente lector corre sobre el mismo servidor donde corre Pathfinder el comando para ejecutarlo es el siguiente:

 $ java -jar pathfinder-agent.jar -w /opt/agente -h[HOST_PATHFINDER] -p[PORT_PATHFINDER] -c[CONTEXT_PATHFINDER] -hh[HOST_HEALTH_PATHFINDER] -hp[PORT_HEALTH_PATHFINDER] -hc[CONTEXT_HEALTH_PATHFINDER]

[[ejecucion_gral]]
=== Puesta en marcha de una datasource
[%hardbreaks]
Iniciar el agente solo hace que el mismo registre en la Plataforma pero no comienza a enviar eventos. 
Para que los eventos comiencen a ser enviados a Pathfinder es necesario ingresar a Pathfinder a la sección de *Agentes* y registrar en el Agente registrado una nueva datasource, donde se especificará el path completo al archivo de eventos. Habiendo hecho esto, aparecerá el botón On/Off para poder comenzar el envío de eventos
 


